name: Deploy Laravel to aaPanel

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} << 'ENDSSH'
          
          git config --global --add safe.directory /www/wwwroot/sistema.ghpu.com.br

          export PATH=/usr/local/node/bin:/usr/local/bin:$PATH
          export NODE_PATH=/usr/local/node/lib/node_modules:$NODE_PATH
          export PATH=/www/server/php/81/bin:$PATH

          cd /www/wwwroot/sistema.ghpu.com.br

          echo "ðŸš€ Pull do GitHub"
          git pull origin main

          echo "ðŸ“¦ Instalando dependÃªncias PHP..."
          composer install --no-interaction --prefer-dist --optimize-autoloader

          echo "ðŸ“¦ Instalando dependÃªncias Node"
          npm install
          npm run build

          echo "ðŸ”§ PermissÃµes"
          chmod -R 775 storage bootstrap/cache
          chown -R www:www storage bootstrap/cache

          echo "ðŸ§¹ Limpando caches"
          php artisan optimize:clear
          php artisan optimize

          echo "ðŸš€ Deploy finalizado!"
          
          ENDSSH